### ISSUE TITLE
Remote Connections

### ISSUE THREAD

**Issue by tgb20** [teachthenet/TeachCraft-Server#2]
Currently we are hosting the server in a remote location and we can use the python script when the server is on the same computer but when we push the server to the remote location we can no longer run the python. Are there any additional ports that need to be opened besides 25565?

**Comment by emeth-** [comment]
Yes - RaspberryJuice opens port 4711 to listen for incoming commands from the mcpi library.

You can change that port here:
https://github.com/teachthenet/TeachCraft-Server/blob/master/config/CanaryRaspberryJuicePlugin/CanaryRaspberryJuicePlugin.cfg#L1

**Comment by tgb20** [comment]
Okay thanks!
